# Generated by Django 3.0.6 on 2020-06-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
