# Generated by Django 3.0.6 on 2020-06-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Me', '0002_education_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='count_edu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='about',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
